# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import object_detect_pb2 as object__detect__pb2


class YoloDetectStub(object):
    """服务定义，这个就是我们在程序中要定义的类了，类名就是YoloDetect
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.v8_detect = channel.unary_unary(
                '/object_detect.YoloDetect/v8_detect',
                request_serializer=object__detect__pb2.Request.SerializeToString,
                response_deserializer=object__detect__pb2.Response.FromString,
                )


class YoloDetectServicer(object):
    """服务定义，这个就是我们在程序中要定义的类了，类名就是YoloDetect
    """

    def v8_detect(self, request, context):
        """函数定义 data_request参数 data_reply返回数据,这个就是在服务器要实现的方法了，是个函数
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YoloDetectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'v8_detect': grpc.unary_unary_rpc_method_handler(
                    servicer.v8_detect,
                    request_deserializer=object__detect__pb2.Request.FromString,
                    response_serializer=object__detect__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'object_detect.YoloDetect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class YoloDetect(object):
    """服务定义，这个就是我们在程序中要定义的类了，类名就是YoloDetect
    """

    @staticmethod
    def v8_detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/object_detect.YoloDetect/v8_detect',
            object__detect__pb2.Request.SerializeToString,
            object__detect__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
